default:
    trainer: ppo
    batch_size: 320
    beta: 2.0e-4
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 256
    lambd: 0.95
    learning_rate: 1.0e-4
    max_steps: 40.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.001
    curiosity_enc_size: 128

